debug: true
db:
 user: "root"
 pass: "root"
 hostname: "localhost"
 dbname: "blocknanny"
 port: 3306
msgs:
 placesleft: "&9You can place %BLOCK% %PLACESLEFT% more times."
 nomore: "&cYou cannot place anymore %BLOCK%s"
limits:
 HOPPER: 10
 